projectTitle = "EnderRelay"
modId = "ender_relay"
githubRepo = "TheEnderCore/EnderRelay"
discordServerInviteId = "KZ5Q364hEg"
authors = [ "TheEnderCore" ]
majorMinecraftVersion = "1.20"
minecraftVersion = "1.20.1"
fabricLoaderVersion = "0.15.3"
fabricApiVersion = "0.91.0+1.20.1"
fabricLangKotlinVersion = "1.10.17+kotlin.1.9.22"
license = "MIT"
modules = [ ]

[mappings]
    # You have 6 mapping types
    # MOJANG: The official Mojang mappings
    # YARN: Yarn mappings
    # PARCHMENT: Parchment mappings
    # QUILT: Quilt mappings
    # MOJPARCH: Parchment layered on top of the official Mojang mappings
    # MOJYARN: Yarn layered on top of the official Mojang mappings
    type = "QUILT"
    version = "1.20.1+build.23"